# Generated by Django 3.2.16 on 2023-03-25 06:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('name', models.CharField(max_length=30, verbose_name='Название категории')),
                ('image', models.ImageField(null=True, upload_to=main.models.upload_to, verbose_name='Изображение категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('slug', models.SlugField(default='', verbose_name='ЧПУ')),
                ('name', models.CharField(default=None, max_length=30, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена товара')),
                ('discount_percent', models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Скидки на товар')),
                ('count', models.PositiveBigIntegerField(default=0, verbose_name='Остаток')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=main.models.upload_to, verbose_name='Изображение товара')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='main.product', verbose_name='Товар')),
            ],
        ),
    ]
